// Each collection: how to list, what columns, and the edit form fields.
// field types: text | textarea | number | checkbox | json (arrays/objects)
export const COLLECTIONS = {
  services: {
    label: 'Services', endpoint: '/services', titleField: 'title',
    columns: ['title', 'summary', 'order'],
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'summary', label: 'Summary', type: 'textarea' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'intro', label: 'Intro paragraph', type: 'textarea' },
      { key: 'groups', label: 'Detail groups (JSON [{heading,items:[]}])', type: 'json' },
      { key: 'icon', label: 'Icon (process/home/industry/robot/vision/ai)', type: 'text' },
      { key: 'features', label: 'Features (JSON array)', type: 'json' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  products: {
    label: 'Products', endpoint: '/products', titleField: 'name',
    columns: ['name', 'category', 'order'],
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'category', label: 'Category (MDMS / Datalogger / …)', type: 'text' },
      { key: 'summary', label: 'Summary', type: 'textarea' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'purpose', label: 'Purpose', type: 'textarea' },
      { key: 'positioning', label: 'Positioning (tagline)', type: 'text' },
      { key: 'buildsOn', label: 'Builds on (e.g. MDMS 2.3)', type: 'text' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'features', label: 'Features (JSON array)', type: 'json' },
      { key: 'specs', label: 'Specs (JSON [{label,value}])', type: 'json' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  projects: {
    label: 'Projects', endpoint: '/projects', titleField: 'title',
    columns: ['title', 'client', 'year'],
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'client', label: 'Client', type: 'text' },
      { key: 'year', label: 'Year', type: 'text' },
      { key: 'summary', label: 'Summary', type: 'textarea' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'video', label: 'Video upload (mp4, max 60MB)', type: 'video' },
      { key: 'videoUrl', label: 'OR YouTube/video link', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  technologies: {
    label: 'Technologies', endpoint: '/technologies', titleField: 'title',
    columns: ['title', 'summary', 'order'],
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'summary', label: 'Summary', type: 'textarea' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'intro', label: 'Intro paragraph', type: 'textarea' },
      { key: 'groups', label: 'Detail groups (JSON [{heading,items:[]}])', type: 'json' },
      { key: 'icon', label: 'Icon (robot/vision/ai)', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  workflow: {
    label: 'Workflow', endpoint: '/workflow', titleField: 'title',
    columns: ['title', 'summary', 'order'],
    fields: [
      { key: 'title', label: 'Step title', type: 'text' },
      { key: 'summary', label: 'One-line', type: 'text' },
      { key: 'intro', label: 'Intro paragraph', type: 'textarea' },
      { key: 'groups', label: 'Groups (JSON [{heading,items:[]}])', type: 'json' },
      { key: 'example', label: 'Example', type: 'textarea' },
      { key: 'output', label: 'Output', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  stats: {
    label: 'Stats', endpoint: '/stats', titleField: 'label',
    columns: ['value', 'label', 'order'],
    fields: [
      { key: 'value', label: 'Value (50+)', type: 'text' },
      { key: 'label', label: 'Label', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
    ],
  },
  industries: {
    label: 'Industries', endpoint: '/industries', titleField: 'title',
    columns: ['title', 'order'],
    fields: [
      { key: 'title', label: 'Industry', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
    ],
  },
  testimonials: {
    label: 'Testimonials', endpoint: '/testimonials', titleField: 'author',
    columns: ['author', 'role'],
    fields: [
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'quote', label: 'Quote', type: 'textarea' },
      { key: 'order', label: 'Order', type: 'number' },
    ],
  },
  posts: {
    label: 'Blog / News', endpoint: '/posts', titleField: 'title',
    columns: ['title', 'category', 'author'],
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'category', label: 'Category (Blog / News)', type: 'text' },
      { key: 'excerpt', label: 'Excerpt (short)', type: 'textarea' },
      { key: 'content', label: 'Content (paragraphs, blank line between)', type: 'textarea' },
      { key: 'coverImage', label: 'Cover image', type: 'image' },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  team: {
    label: 'Leadership', endpoint: '/team', titleField: 'name',
    columns: ['name', 'role'],
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'photo', label: 'Photo', type: 'image' },
      { key: 'bio', label: 'Bio (short, shown on card)', type: 'textarea' },
      { key: 'details', label: 'Full profile (paragraphs, blank line between)', type: 'textarea' },
      { key: 'linkedin', label: 'LinkedIn URL', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  openings: {
    label: 'Careers', endpoint: '/openings', titleField: 'title',
    columns: ['title', 'location', 'type'],
    fields: [
      { key: 'title', label: 'Job title', type: 'text' },
      { key: 'department', label: 'Department (e.g. Automation / Vision / Software)', type: 'text' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'type', label: 'Type (Full-time / Contract / Internship)', type: 'text' },
      { key: 'experience', label: 'Experience (e.g. 2–5 years)', type: 'text' },
      { key: 'salary', label: 'Salary (optional, e.g. ₹4–7 LPA)', type: 'text' },
      { key: 'positions', label: 'No. of openings', type: 'number' },
      { key: 'summary', label: 'Short summary (one line, shown on card)', type: 'text' },
      { key: 'description', label: 'Full description (paragraphs)', type: 'textarea' },
      { key: 'responsibilities', label: 'Responsibilities (one per line)', type: 'lines' },
      { key: 'requirements', label: 'Requirements / qualification (one per line)', type: 'lines' },
      { key: 'skills', label: 'Skills (one per line)', type: 'lines' },
      { key: 'benefits', label: 'What we offer (one per line)', type: 'lines' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  clients: {
    label: 'Clients', endpoint: '/clients', titleField: 'name',
    columns: ['name', 'url'],
    fields: [
      { key: 'name', label: 'Client name', type: 'text' },
      { key: 'logo', label: 'Logo', type: 'image' },
      { key: 'url', label: 'Website URL (optional)', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
};
